[project]
name = "miditoyz"
version = "0.1.0"
description = "care and feeding for you midi song collection"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.2",
    "jinja2>=3.1.6",
    "mido>=1.3.3",
    "python-rtmidi>=1.5.8",
    "typer>=0.15.2",
]
